call plug#begin('~/.vim/plugged')
"Plug 'Valloric/YouCompleteMe'
Plug 'ycm-core/YouCompleteMe'
Plug 'davidhalter/jedi-vim'
"Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install_sync() } }
Plug 'plasticboy/vim-markdown'   " 语法高亮
"Plug 'mattn/emmet-vim'      " html, css插件
"Plug 'ferreum/completor-tmux'
Plug 'yianwillis/vimcdoc'
call plug#end()
filetype plugin indent on


" ycm
" 补全后自动关闭预览窗口
let g:ycm_autoclose_preview_window_after_completion = 1
" 离开插入模式后自动关闭预览窗口
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
" 补全完成时预览窗口自动消失
augroup complete
   autocmd!
     autocmd CompleteDone * pclose
augroup end

" jedi sets
let g:jedi#completions_command = "<C-N>"   " 往下选择
let g:jedi#popup_select_first = 3
let g:jedi#auto_initialization = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#use_splits_not_buffers = "left"

"-d: 转向定义, c-o返回"

" YCM sets
""let g:ycm_min_num_of_chars_for_completion = 2
""let g:ycm_autoclose_preview_window_after_completion = 1
""let g:ycm_seed_identifiers_with_syntax = 1

""map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>


" emmet-vim 配置 """"""""""""""""""""""""""""""""""""""""""""
""let g:user_emmet_mode='inv'                   " 在所有模式中启用emmet
""let g:user_emmet_leader_key='<C-Y>'           " 定义关键key
" 仅为html/css启用
""let g:user_emmet_install_global = 0
""autocmd FileType html,css EmmetInstall

" emmet-vim 配置 """"""""""""""""""""""""""""""""""""""""""""

" markdown set
let g:mkdp_browser = '/usr/bin/google-chrome'
"let g:mkdp_path_to_chrome = "google-chrome"
" 设置 chrome 浏览器的路径（或是启动 chrome（或其他现代浏览器）的命令）
" 如果设置了该参数, g:mkdp_browserfunc 将被忽略

"let g:mkdp_browserfunc = 'MKDP_browserfunc_default'
" vim 回调函数, 参数为要打开的 url

let g:mkdp_auto_start = 1
" 设置为 1 可以在打开 markdown 文件的时候自动打开浏览器预览，只在打开
" markdown 文件的时候打开一次

let g:mkdp_auto_open = 1
" 设置为 1 在编辑 markdown 的时候检查预览窗口是否已经打开，否则自动打开预
" 览窗口

let g:mkdp_auto_close = 0
" 在切换 buffer 的时候自动关闭预览窗口，设置为 0 则在切换 buffer 的时候不
" 自动关闭预览窗口

let g:mkdp_refresh_slow = 0
" 设置为 1 则只有在保存文件，或退出插入模式的时候更新预览，默认为 0，实时
" 更新预览

let g:mkdp_command_for_global = 0
" 设置为 1 则所有文件都可以使用 MarkdownPreview 进行预览，默认只有 markdown
" 文件可以使用改命令

let g:mkdp_open_to_the_world = 0
" 设置为 1, 在使用的网络中的其他计算机也能访问预览页面
" 默认只监听本地（127.0.0.1），其他计算机不能访问

" markdown set

set bg=dark
syntax enable

"  Line number display 
set number
set relativenumber  "rnu
set numberwidth=2

" Indentation
set foldmethod=indent
"set foldcolumn=4
set tabstop=2
set shiftwidth=2
"set autoindent   "自动缩进
set smartindent
set expandtab
set nowrap
set sidescroll=20

set modelines=10

" Automatic Completion
noremap! ( ()<left>
noremap! [ []<left>
noremap! { {}<left>
noremap! < <><left>
noremap! ' ''<left>
noremap! " ""<left>
inoremap , , 

" map
let mapleader = "-"
" 将单词转为大写
noremap <leader>U <esc>viwgUe
inoremap <leader>U <esc>viwgUea
" 给单词加上引号和括号
inoremap <leader>" <esc>bi"<esc>lea"
inoremap <leader>' <esc>bi'<esc>lea'
inoremap <leader>< <esc>bi<<esc>lea>
inoremap <leader>( <esc>bi(<esc>lea)
inoremap <leader>[ <esc>bi[<esc>lea]
inoremap <leader>{ <esc>bi{<esc>lea}
nnoremap <leader>" bi"<esc>lea"<esc>
nnoremap <leader>' bi'<esc>lea'<esc>
nnoremap <leader>< bi<<esc>lea><esc>
nnoremap <leader>( bi(<esc>lea)<esc>
nnoremap <leader>[ bi[<esc>lea]<esc>
nnoremap <leader>{ bi{<esc>lea}<esc>
" 为文件加入时间戳
nnoremap <F2> o# Date: <Esc>:read !date<CR>kJ
nnoremap <F3> <Esc>:set expandtab<CR>:%retab<CR>
nnoremap <F4> <Esc>:set foldlevel=100<CR>


" Completion display
set showmatch matchtime=10
" Lookup setting
set incsearch
set hlsearch           "高亮
set wrapscan

" Bottom information
set showmode
set showcmd
set ruler
set cmdheight=1


" 添加各类文件信息
" html
autocmd BufNewFile *.html,*.htm exec ":call Set_html_title()"
func Set_html_title()
  call setline(1, "<!DOCTYPE html>")
  call setline(2, "<html lang=\"en\">")
  call setline(3, "<head>")
  call setline(4, "  <meta charset=\"UTF-8\">")
  call setline(5, "  <title>Title</title>")
  call setline(6, "</head>")
  call setline(7, "<body>")
  call setline(8, "  <a></a>")
  call setline(9, "</body>")
  call setline(10, "</html>")
endfunc

" python
autocmd BufNewFile *.py exec ":call Set_python_title()"
func Set_python_title()
  call setline(1,"#!/usr/bin/env python")
  call setline(2,"# *-* coding:utf8 *-*")
  call setline(3,"# sky")
  call setline(4,"")
  call setline(5,"def main():")
  call setline(6,"    ")
  call setline(7,"if __name__ == \"__main__\":")
  call setline(8,"    main()")
endfunc

" shell
autocmd BufNewFile *.sh exec ":call Set_shell_title()"
func Set_shell_title()
  call setline(1,"#!/bin/bash")
  call setline(2,"# sky")
endfunc

"func SetTitle()
"  if &filetype == 'python'
"    "call setline(1,"#!/usr/bin/env python")
"    "call setline(2,"# coding:utf8")
"    "call SetComment_python()
"    "call setline(4,"")
"    "call setline(5,"import sys")
"    "call setline(6,"")
"    "call setline(7,"reload(sys)")
"    "call setline(8,"sys.setdefaultencoding('utf8')")
"    "call setline(9,"")
"    "call setline(10,"if __name__ == \"__main__\":")
"    call setline(1,"#!/usr/bin/env python")
"    call setline(2,"# coding:utf8")
"    call SetComment_python()
"    call setline(4,"")
"    call setline(5,"if __name__ == \"__main__\":")
"  elseif &filetype == 'sh'
"    call setline(1,"#!/bin/bash")
"    call SetComment_shell()
"  endif
"endfunc

" plugin
"set nocompatible
"filetype plugin on

" encoding
let &termencoding=&encoding
set fileencodings=utf-8,gbk
set fileformats=unix,dos,mac
" 超过10min中未操作则自动保存
set updatetime=600000
autocmd CursorHold,CursorHoldI *.* :w!


"  error correction 
noremap! ： :
noremap! ， , 
noremap! 。 . 
noremap! × *
noremap! ” ""<left>
noremap! （ ()<left>


