# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/opt/python3/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="sky"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git 
  zsh-syntax-highlighting 
  #zsh-autosuggestions 
  safe-paste
  extract
  z
  vi-mode
  web-search
)


source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#alias ssh_company="ssh -p '996' 'root@117.184.59.230'"
alias rm="mv -f --target-directory=/tmp/"
alias automount="sshfs -o nonempty,reconnect,allow_other -p 22 root@192.168.1.97:/code/autodep/ /mnt/autodep/; cd /mnt/autodep"
alias proxy="export http_proxy='http://127.0.0.1:8118'; export https_proxy='https://127.0.0.1:8118'"
alias unproxy="unset http_proxy; unset https_proxy"
#alias proxy="export ALL_PROXY='socks5://127.0.0.1:1080'"
alias chrome_proxy='google-chrome -user-data-dir="/home/sky/.google-chrome/proxy" --proxy-server=socks5://127.0.0.1:1080 &'
#alias chrome='google-chrome -user-data-dir="/home/sky/.google-chrome/noproxy" &'

# 配置direnv
eval "$(direnv hook zsh)"
show_virtual_env() {
  if [ -n "$VIRTUAL_ENV" ]; then
    echo "($(echo $(basename $VIRTUAL_ENV) | cut -d"-" -f1))"
  fi
}
export PROMPT='$(show_virtual_env)'$PROMPT 

# 按键绑定
bindkey ',' autosuggest-accept
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

# 显示编辑模式
#VIMODE='-- INSERT --'
#function zle-line-init zle-keymap-select {
#    VIMODE="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
#    zle reset-prompt
#}
#zle -N zle-line-init 
#zle -N zle-keymap-select
#RPROMPT='%{$fg[green]%}${VIMODE}%{$reset_color%}'


# Modal cursor color for vi's insert/normal modes. 
# 游标显示编辑模式
#zle-keymap-select() { 
#	if [ $KEYMAP = vicmd ]; then 
#    echo -ne "\033]12;Yellow\007" 
#    echo -ne "\033[2 q" 
#	else 
#    echo -ne "\033]12;Red\007" 
#    echo -ne "\033[4 q" 
#    fi 
#} 
#zle -N zle-keymap-select 
#zle-line-init() { 
#	zle -K viins 
#	echo -ne "\033]12;Red\007" 
#	echo -ne "\033[4 q" 
#} 
#zle -N zle-line-init 

#export -f show_virtual_env
#PROMPT='$(show_virtual_env)'$PROMPT
